package mx.uv.internshipprogramsystem.logic.security;

public enum Permission {
    REGISTER_PROFESSOR,
    CONSULT_PROFESSOR,
    UPDATE_PROFESSOR,
    CHANGE_PROFESSOR_STATUS,

    REGISTER_INTERN,
    CONSULT_INTERN,
    UPDATE_INTERN,
    CHANGE_INTERN_STATUS,

    REGISTER_ORGANIZATION,
    CONSULT_ORGANIZATION,

    REGISTER_PROJECT_RESPONSIBLE,
    CONSULT_PROJECT_RESPONSIBLE,

    REGISTER_PROJECT,
    CONSULT_PROJECT,
    UPDATE_PROJECT,
    ADD_PROJECT_ACTIVITIES,
    REQUEST_PROJECT,
    ASSIGN_PROJECT,
    DELETE_PROJECT,
    VALIDATE_PROJECT,

    UPLOAD_INITIAL_FORMATS,
    VALIDATE_INITIAL_FORMATS,

    UPLOAD_ORGANIZATION_EVALUATION,
    UPLOAD_SELF_EVALUATION,
    GENERATE_SELF_EVALUATION,
    PRINT_SELF_EVALUATION,
    CONSULT_SELF_EVALUATION,

    EVALUATE_REPORT,
    UPLOAD_REPORT,
    GENERATE_REPORT,
    PRINT_REPORT,
    CONSULT_REPORT,
    GENERATE_FINAL_REPORT,

    REGISTER_EDUCATIONAL_EXPERIENCE,
    ASSIGN_EDUCATIONAL_EXPERIENCE
}